name: Assign new issues to the test project
on:
  issues:
    types: [ opened, reopened ]
jobs:
  assign:
    name: Assign to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # required to find all branches
          fetch-depth: 0
      - name: Assign to project
        uses: zeebe-io/project-action@develop
        with:
          github_token: ${{ secrets.ORG_TOKEN }}
          project_type: "org"
          project_owner: "zeebe-io"
          project_name: "Zeebe"
